---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/livres
  label: Livres
  create: all
  match: "**/*"
  templates:
  - livre
- type: directory
  path: content/videos
  label: Videos
  create: all
  match: "**/*"
  templates:
  - video
- type: directory
  path: content/evenements
  label: Evenements
  create: all
  match: "**/*"
  templates:
  - evenement
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.52'
